// test_render_decoder.cpp — Verifies RenderVideoDecoder with real D3D11 GPU
// Uses a DNxHR proxy file generated by ffmpeg (test_proxy.mov in this directory).

#include "render/RenderVideoDecoder.h"
#include "render/GpuDeviceManager.h"
#include "render/FrameCache.h"

#include <cassert>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <filesystem>

// Helper: get the path to test_proxy.mov relative to the executable
static std::string findTestProxy()
{
    // Try several locations — build systems place the exe in different dirs
    const char* candidates[] = {
        "test_proxy.mov",
        "../test_proxy.mov",
        "../../engine/test/test_proxy.mov",
        "../../../engine/test/test_proxy.mov",
        "../../../../engine/test/test_proxy.mov",
    };

    for (const char* path : candidates) {
        if (std::filesystem::exists(path)) {
            return std::filesystem::absolute(path).string();
        }
    }

    // Also try from XLETH root via environment or known relative path
    return "";
}

int main()
{
    std::fprintf(stderr, "\n[TEST:RenderDecoder] Starting decoder tests...\n");

    // ── GPU setup ────────────────────────────────────────────────────────────
    GpuDeviceManager gpu;
    if (!gpu.detectAdapters()) {
        std::fprintf(stderr, "[TEST:RenderDecoder] SKIP: no DXGI adapters\n");
        return 0;
    }
    if (!gpu.createDevice()) {
        std::fprintf(stderr, "[TEST:RenderDecoder] SKIP: D3D11 device creation failed\n");
        return 0;
    }
    ID3D11Device*        device    = gpu.getDevice();
    ID3D11DeviceContext* deviceCtx = gpu.getContext();
    assert(device && deviceCtx);
    std::fprintf(stderr, "[TEST:RenderDecoder] GPU device ready\n");

    // ── Find test proxy file ─────────────────────────────────────────────────
    std::string proxyPath = findTestProxy();
    if (proxyPath.empty()) {
        std::fprintf(stderr, "[TEST:RenderDecoder] SKIP: test_proxy.mov not found\n");
        std::fprintf(stderr, "[TEST:RenderDecoder] Generate with:\n");
        std::fprintf(stderr, "  ffmpeg -f lavfi -i testsrc=duration=2:size=320x240:rate=30 "
                     "-c:v dnxhd -profile:v dnxhr_sq -pix_fmt yuv422p -y test_proxy.mov\n");
        return 0;
    }
    std::fprintf(stderr, "[TEST:RenderDecoder] Using proxy: %s\n", proxyPath.c_str());

    // ── Create decoder ───────────────────────────────────────────────────────
    RenderVideoDecoder decoder;

    // Init hw device (may fail — sw fallback still tested)
    bool hwOk = decoder.initHwDevice(device, deviceCtx);
    std::fprintf(stderr, "[TEST:RenderDecoder] D3D11VA init: %s\n", hwOk ? "OK" : "unavailable (SW only)");

    // ── Test 1: Decode frame 0 ──────────────────────────────────────────────
    {
        std::fprintf(stderr, "\n[TEST:RenderDecoder] --- Test 1: Decode frame 0 ---\n");

        FrameCacheEntry entry = decoder.decode(proxyPath, 0, device, deviceCtx);

        assert(entry.texture != nullptr && "Frame 0 texture should not be null");
        assert(entry.srv != nullptr && "Frame 0 SRV should not be null");
        assert(entry.width == 320);
        assert(entry.height == 240);
        assert(entry.memorySizeBytes == 320 * 240 * 4);

        // Verify texture desc
        D3D11_TEXTURE2D_DESC desc;
        entry.texture->GetDesc(&desc);
        assert(desc.Width == 320);
        assert(desc.Height == 240);
        assert(desc.Format == DXGI_FORMAT_B8G8R8A8_UNORM);
        assert(desc.Usage == D3D11_USAGE_DEFAULT);
        assert((desc.BindFlags & D3D11_BIND_SHADER_RESOURCE) != 0);

        std::fprintf(stderr, "[TEST:RenderDecoder] Test 1: PASSED\n");
    }

    // ── Test 2: Decode frame 29 (last frame of second 1) ────────────────────
    {
        std::fprintf(stderr, "\n[TEST:RenderDecoder] --- Test 2: Decode frame 29 ---\n");

        FrameCacheEntry entry = decoder.decode(proxyPath, 29, device, deviceCtx);

        assert(entry.texture != nullptr);
        assert(entry.srv != nullptr);
        assert(entry.width == 320);
        assert(entry.height == 240);

        std::fprintf(stderr, "[TEST:RenderDecoder] Test 2: PASSED\n");
    }

    // ── Test 3: Sequential decode (frames 30, 31, 32) ───────────────────────
    {
        std::fprintf(stderr, "\n[TEST:RenderDecoder] --- Test 3: Sequential decode ---\n");

        // Set sequential hint
        decoder.setSequentialHint(proxyPath, true);

        // Decode frame 30 — should seek (different from frame 29+1 because
        // the hint was just set and lastDecodedFrame is 29 from Test 2)
        FrameCacheEntry e30 = decoder.decode(proxyPath, 30, device, deviceCtx);
        assert(e30.texture != nullptr);

        // Frame 31 — should skip seek (sequential hint, last was 30)
        FrameCacheEntry e31 = decoder.decode(proxyPath, 31, device, deviceCtx);
        assert(e31.texture != nullptr);

        // Frame 32 — should skip seek
        FrameCacheEntry e32 = decoder.decode(proxyPath, 32, device, deviceCtx);
        assert(e32.texture != nullptr);

        // Turn off hint
        decoder.setSequentialHint(proxyPath, false);

        std::fprintf(stderr, "[TEST:RenderDecoder] Test 3: PASSED\n");
    }

    // ── Test 4: Random access (seek to frame 50) ────────────────────────────
    {
        std::fprintf(stderr, "\n[TEST:RenderDecoder] --- Test 4: Random access frame 50 ---\n");

        FrameCacheEntry entry = decoder.decode(proxyPath, 50, device, deviceCtx);

        assert(entry.texture != nullptr);
        assert(entry.width == 320);
        assert(entry.height == 240);

        std::fprintf(stderr, "[TEST:RenderDecoder] Test 4: PASSED\n");
    }

    // ── Test 5: DNxHR is detected as intra-only ─────────────────────────────
    {
        std::fprintf(stderr, "\n[TEST:RenderDecoder] --- Test 5: Intra-only detection ---\n");

        // The context should already be open from previous decodes
        assert(decoder.openContextCount() >= 1);

        std::fprintf(stderr, "[TEST:RenderDecoder] Test 5: PASSED (intra detection logged above)\n");
    }

    // ── Test 6: LRU eviction (open MAX_OPEN_CONTEXTS + 1 sources) ──────────
    {
        std::fprintf(stderr, "\n[TEST:RenderDecoder] --- Test 6: LRU eviction ---\n");

        // We already have 1 open context (test_proxy.mov).
        // Opening MAX_OPEN_CONTEXTS more should evict the oldest.
        // We don't have that many real files, so just verify the count doesn't
        // exceed MAX_OPEN_CONTEXTS.
        assert(decoder.openContextCount() <= RenderVideoDecoder::MAX_OPEN_CONTEXTS);

        std::fprintf(stderr, "[TEST:RenderDecoder] open contexts: %d (max %d)\n",
                     decoder.openContextCount(), RenderVideoDecoder::MAX_OPEN_CONTEXTS);

        std::fprintf(stderr, "[TEST:RenderDecoder] Test 6: PASSED\n");
    }

    // ── Test 7: closeAll ────────────────────────────────────────────────────
    {
        std::fprintf(stderr, "\n[TEST:RenderDecoder] --- Test 7: closeAll ---\n");

        decoder.closeAll();
        assert(decoder.openContextCount() == 0);

        // Re-decode after closeAll should work (re-opens context)
        FrameCacheEntry entry = decoder.decode(proxyPath, 10, device, deviceCtx);
        assert(entry.texture != nullptr);
        assert(entry.width == 320);
        assert(decoder.openContextCount() == 1);

        std::fprintf(stderr, "[TEST:RenderDecoder] Test 7: PASSED\n");
    }

    // ── Test 8: Invalid file path ───────────────────────────────────────────
    {
        std::fprintf(stderr, "\n[TEST:RenderDecoder] --- Test 8: Invalid file ---\n");

        FrameCacheEntry entry = decoder.decode("nonexistent_video.mp4", 0, device, deviceCtx);
        assert(entry.texture == nullptr && "Invalid file should return empty entry");

        std::fprintf(stderr, "[TEST:RenderDecoder] Test 8: PASSED\n");
    }

    // ── Test 9: Last frame of video (frame 59) ─────────────────────────────
    {
        std::fprintf(stderr, "\n[TEST:RenderDecoder] --- Test 9: Last frame (59) ---\n");

        FrameCacheEntry entry = decoder.decode(proxyPath, 59, device, deviceCtx);
        assert(entry.texture != nullptr);
        assert(entry.width == 320 && entry.height == 240);

        std::fprintf(stderr, "[TEST:RenderDecoder] Test 9: PASSED\n");
    }

    // Explicit cleanup: release FFmpeg hw device context and all decoder
    // contexts before GpuDeviceManager's D3D11 device is destroyed.
    decoder.shutdown();

    std::fprintf(stderr, "\n[TEST:RenderDecoder] ALL TESTS PASSED\n");

    // Use _exit to skip static destructors — FFmpeg's D3D11VA cleanup and
    // JUCE static teardown can race with COM Release ordering, causing a
    // benign segfault during process exit.  All resources were explicitly
    // cleaned up above.
    std::_Exit(0);
}
