#include "GridCompositor.h"

#include <algorithm>
#include <cassert>
#include <cstdio>
#include <cstring>

// Precompiled shader bytecode (generated by fxc.exe from GridComposite.hlsl)
#include "shaders/GridCompositeVS.h"
#include "shaders/GridCompositePS.h"

// Effect shader bytecode (placeholders — actual implementations in later prompts)
#include "shaders/FX_DesaturationPS.h"
#include "shaders/FX_TintPS.h"
#include "shaders/FX_BrightnessContrastPS.h"
#include "shaders/FX_TVSimulatorPS.h"
#include "shaders/FX_ZoomPanRotationPS.h"

#include "model/TimelineTypes.h"  // VisualEffect

// ---------------------------------------------------------------------------
// HRESULT → short text for readback failure diagnostics
// ---------------------------------------------------------------------------
static const char* hrText(HRESULT hr) {
    switch (static_cast<unsigned int>(hr)) {
        case 0x887A0001U: return "DXGI_ERROR_WAS_STILL_DRAWING";
        case 0x887A0005U: return "DXGI_ERROR_DEVICE_REMOVED";
        case 0x887A0006U: return "DXGI_ERROR_DEVICE_HUNG";
        case 0x887A0007U: return "DXGI_ERROR_DEVICE_RESET";
        case 0x80070057U: return "E_INVALIDARG";
        case 0x80004003U: return "E_POINTER";
        case 0x8007000EU: return "E_OUTOFMEMORY";
        default:          return "(unknown)";
    }
}

// ---------------------------------------------------------------------------
// Vertex layout for the fullscreen quad
// ---------------------------------------------------------------------------
struct QuadVertex {
    float x, y;   // NDC position
    float u, v;   // UV
};

// ===========================================================================
// Lifecycle
// ===========================================================================

GridCompositor::GridCompositor() = default;

GridCompositor::~GridCompositor()
{
    shutdown();
}

bool GridCompositor::init(ID3D11Device* device, ID3D11DeviceContext* deviceCtx,
                           int width, int height)
{
    if (!device || !deviceCtx || width <= 0 || height <= 0) {
        std::fprintf(stderr, "[Compositor] Init failed: invalid parameters\n");
        return false;
    }

    shutdown();  // clean up any previous state

    device_    = device;
    deviceCtx_ = deviceCtx;
    width_     = width;
    height_    = height;

    if (!createRenderTarget())   return false;
    if (!createStagingTexture()) return false;
    if (!createShaders())        return false;
    if (!createGeometry())       return false;
    if (!createPipelineState())  return false;

    // Initialize effect shader cache (placeholder shaders for now)
    if (!effectShaders_.init(device_)) {
        std::fprintf(stderr, "[Compositor] WARNING: Effect shaders failed to init — chain processing disabled\n");
        // Non-fatal: compositor works without effects
    }

    initialized_ = true;
    std::fprintf(stderr, "[Compositor] Init: %dx%d render target, BGRA, blend=SRC_ALPHA/INV_SRC_ALPHA\n",
                 width_, height_);
    return true;
}

void GridCompositor::shutdown()
{
    effectShaders_.shutdown();
    rtPool_.clear();

    renderTarget_.Reset();
    renderTargetRTV_.Reset();
    renderTargetSRV_.Reset();
    stagingTextures_[0].Reset();
    stagingTextures_[1].Reset();
    readbackFrameCount_ = 0;
    lastReadbackHR_     = S_OK;
    vertexShader_.Reset();
    pixelShader_.Reset();
    inputLayout_.Reset();
    vertexBuffer_.Reset();
    indexBuffer_.Reset();
    blendState_.Reset();
    samplerState_.Reset();
    constantBuffer_.Reset();
    globalConstantBuffer_.Reset();
    rasterizerState_.Reset();
    depthStencilState_.Reset();

    device_      = nullptr;
    deviceCtx_   = nullptr;
    width_       = 0;
    height_      = 0;
    initialized_ = false;
}

// ===========================================================================
// Resource creation
// ===========================================================================

bool GridCompositor::createRenderTarget()
{
    D3D11_TEXTURE2D_DESC desc = {};
    desc.Width            = static_cast<UINT>(width_);
    desc.Height           = static_cast<UINT>(height_);
    desc.MipLevels        = 1;
    desc.ArraySize        = 1;
    desc.Format           = DXGI_FORMAT_B8G8R8A8_UNORM;
    desc.SampleDesc.Count = 1;
    desc.Usage            = D3D11_USAGE_DEFAULT;
    desc.BindFlags        = D3D11_BIND_RENDER_TARGET | D3D11_BIND_SHADER_RESOURCE;

    HRESULT hr = device_->CreateTexture2D(&desc, nullptr, &renderTarget_);
    if (FAILED(hr)) {
        std::fprintf(stderr, "[Compositor] Failed to create render target, HR=0x%08X\n",
                     static_cast<unsigned int>(hr));
        return false;
    }

    hr = device_->CreateRenderTargetView(renderTarget_.Get(), nullptr, &renderTargetRTV_);
    if (FAILED(hr)) {
        std::fprintf(stderr, "[Compositor] Failed to create RTV, HR=0x%08X\n",
                     static_cast<unsigned int>(hr));
        return false;
    }

    hr = device_->CreateShaderResourceView(renderTarget_.Get(), nullptr, &renderTargetSRV_);
    if (FAILED(hr)) {
        std::fprintf(stderr, "[Compositor] Failed to create RT SRV, HR=0x%08X\n",
                     static_cast<unsigned int>(hr));
        return false;
    }

    return true;
}

bool GridCompositor::createStagingTexture()
{
    D3D11_TEXTURE2D_DESC desc = {};
    desc.Width            = static_cast<UINT>(width_);
    desc.Height           = static_cast<UINT>(height_);
    desc.MipLevels        = 1;
    desc.ArraySize        = 1;
    desc.Format           = DXGI_FORMAT_B8G8R8A8_UNORM;
    desc.SampleDesc.Count = 1;
    desc.Usage            = D3D11_USAGE_STAGING;
    desc.CPUAccessFlags   = D3D11_CPU_ACCESS_READ;
    // BindFlags must be 0 for staging textures — D3D11 spec requirement.

    std::fprintf(stderr,
        "[Compositor] Staging ring: creating 2x %ux%u BGRA STAGING CPU_READ "
        "bindFlags=0x%X expectedBytesEach=%zu\n",
        desc.Width, desc.Height, desc.BindFlags,
        static_cast<size_t>(desc.Width) * desc.Height * 4u);

    for (int i = 0; i < 2; ++i) {
        HRESULT hr = device_->CreateTexture2D(&desc, nullptr, &stagingTextures_[i]);
        if (FAILED(hr)) {
            std::fprintf(stderr,
                "[Compositor] Failed to create staging texture[%d], HR=0x%08X\n",
                i, static_cast<unsigned int>(hr));
            return false;
        }
    }

    return true;
}

bool GridCompositor::createShaders()
{
    // Vertex shader from precompiled bytecode
    HRESULT hr = device_->CreateVertexShader(
        g_GridCompositeVS, sizeof(g_GridCompositeVS), nullptr, &vertexShader_);
    if (FAILED(hr)) {
        std::fprintf(stderr, "[Compositor] Shader compiled: vertex=FAIL pixel=?\n");
        return false;
    }

    // Pixel shader from precompiled bytecode
    hr = device_->CreatePixelShader(
        g_GridCompositePS, sizeof(g_GridCompositePS), nullptr, &pixelShader_);
    if (FAILED(hr)) {
        std::fprintf(stderr, "[Compositor] Shader compiled: vertex=OK pixel=FAIL\n");
        return false;
    }

    // Input layout matching VSInput: POSITION (float2) + TEXCOORD0 (float2)
    D3D11_INPUT_ELEMENT_DESC layoutDesc[] = {
        { "POSITION", 0, DXGI_FORMAT_R32G32_FLOAT, 0, 0,
          D3D11_INPUT_PER_VERTEX_DATA, 0 },
        { "TEXCOORD", 0, DXGI_FORMAT_R32G32_FLOAT, 0, 8,
          D3D11_INPUT_PER_VERTEX_DATA, 0 },
    };
    hr = device_->CreateInputLayout(
        layoutDesc, 2,
        g_GridCompositeVS, sizeof(g_GridCompositeVS),
        &inputLayout_);
    if (FAILED(hr)) {
        std::fprintf(stderr, "[Compositor] Failed to create input layout, HR=0x%08X\n",
                     static_cast<unsigned int>(hr));
        return false;
    }

    std::fprintf(stderr, "[Compositor] Shader compiled: vertex=OK pixel=OK\n");
    return true;
}

bool GridCompositor::createGeometry()
{
    // Fullscreen quad: 4 vertices covering NDC (-1,-1) to (1,1)
    // UV: (0,0) at top-left, (1,1) at bottom-right
    // Note: D3D11 NDC has Y+ up, UV has V+ down → flip V in vertex data
    QuadVertex vertices[] = {
        { -1.0f,  1.0f,  0.0f, 0.0f },  // top-left
        {  1.0f,  1.0f,  1.0f, 0.0f },  // top-right
        {  1.0f, -1.0f,  1.0f, 1.0f },  // bottom-right
        { -1.0f, -1.0f,  0.0f, 1.0f },  // bottom-left
    };

    D3D11_BUFFER_DESC vbDesc = {};
    vbDesc.Usage          = D3D11_USAGE_IMMUTABLE;
    vbDesc.ByteWidth      = sizeof(vertices);
    vbDesc.BindFlags      = D3D11_BIND_VERTEX_BUFFER;

    D3D11_SUBRESOURCE_DATA vbData = {};
    vbData.pSysMem = vertices;

    HRESULT hr = device_->CreateBuffer(&vbDesc, &vbData, &vertexBuffer_);
    if (FAILED(hr)) {
        std::fprintf(stderr, "[Compositor] Failed to create vertex buffer, HR=0x%08X\n",
                     static_cast<unsigned int>(hr));
        return false;
    }

    // Index buffer: 2 triangles (6 indices)
    uint16_t indices[] = { 0, 1, 2,  0, 2, 3 };

    D3D11_BUFFER_DESC ibDesc = {};
    ibDesc.Usage          = D3D11_USAGE_IMMUTABLE;
    ibDesc.ByteWidth      = sizeof(indices);
    ibDesc.BindFlags      = D3D11_BIND_INDEX_BUFFER;

    D3D11_SUBRESOURCE_DATA ibData = {};
    ibData.pSysMem = indices;

    hr = device_->CreateBuffer(&ibDesc, &ibData, &indexBuffer_);
    if (FAILED(hr)) {
        std::fprintf(stderr, "[Compositor] Failed to create index buffer, HR=0x%08X\n",
                     static_cast<unsigned int>(hr));
        return false;
    }

    return true;
}

bool GridCompositor::createPipelineState()
{
    // Alpha blend state: SRC_ALPHA / INV_SRC_ALPHA
    D3D11_BLEND_DESC blendDesc = {};
    blendDesc.RenderTarget[0].BlendEnable           = TRUE;
    blendDesc.RenderTarget[0].SrcBlend               = D3D11_BLEND_SRC_ALPHA;
    blendDesc.RenderTarget[0].DestBlend              = D3D11_BLEND_INV_SRC_ALPHA;
    blendDesc.RenderTarget[0].BlendOp                = D3D11_BLEND_OP_ADD;
    blendDesc.RenderTarget[0].SrcBlendAlpha          = D3D11_BLEND_ONE;
    blendDesc.RenderTarget[0].DestBlendAlpha         = D3D11_BLEND_INV_SRC_ALPHA;
    blendDesc.RenderTarget[0].BlendOpAlpha           = D3D11_BLEND_OP_ADD;
    blendDesc.RenderTarget[0].RenderTargetWriteMask  = D3D11_COLOR_WRITE_ENABLE_ALL;

    HRESULT hr = device_->CreateBlendState(&blendDesc, &blendState_);
    if (FAILED(hr)) {
        std::fprintf(stderr, "[Compositor] Failed to create blend state, HR=0x%08X\n",
                     static_cast<unsigned int>(hr));
        return false;
    }

    // Linear sampler with clamp
    D3D11_SAMPLER_DESC samplerDesc = {};
    samplerDesc.Filter         = D3D11_FILTER_MIN_MAG_MIP_LINEAR;
    samplerDesc.AddressU       = D3D11_TEXTURE_ADDRESS_CLAMP;
    samplerDesc.AddressV       = D3D11_TEXTURE_ADDRESS_CLAMP;
    samplerDesc.AddressW       = D3D11_TEXTURE_ADDRESS_CLAMP;
    samplerDesc.ComparisonFunc = D3D11_COMPARISON_NEVER;
    samplerDesc.MaxLOD         = D3D11_FLOAT32_MAX;

    hr = device_->CreateSamplerState(&samplerDesc, &samplerState_);
    if (FAILED(hr)) {
        std::fprintf(stderr, "[Compositor] Failed to create sampler, HR=0x%08X\n",
                     static_cast<unsigned int>(hr));
        return false;
    }

    // Constant buffer (CellConstants, 32 bytes)
    D3D11_BUFFER_DESC cbDesc = {};
    cbDesc.Usage          = D3D11_USAGE_DYNAMIC;
    cbDesc.ByteWidth      = sizeof(CellConstants);
    cbDesc.BindFlags      = D3D11_BIND_CONSTANT_BUFFER;
    cbDesc.CPUAccessFlags = D3D11_CPU_ACCESS_WRITE;

    hr = device_->CreateBuffer(&cbDesc, nullptr, &constantBuffer_);
    if (FAILED(hr)) {
        std::fprintf(stderr, "[Compositor] Failed to create constant buffer, HR=0x%08X\n",
                     static_cast<unsigned int>(hr));
        return false;
    }

    // Global constant buffer (GlobalConstants, 16 bytes) — updated once per frame
    D3D11_BUFFER_DESC gcbDesc = {};
    gcbDesc.Usage          = D3D11_USAGE_DYNAMIC;
    gcbDesc.ByteWidth      = sizeof(GlobalConstants);
    gcbDesc.BindFlags      = D3D11_BIND_CONSTANT_BUFFER;
    gcbDesc.CPUAccessFlags = D3D11_CPU_ACCESS_WRITE;

    hr = device_->CreateBuffer(&gcbDesc, nullptr, &globalConstantBuffer_);
    if (FAILED(hr)) {
        std::fprintf(stderr, "[Compositor] Failed to create global constant buffer, HR=0x%08X\n",
                     static_cast<unsigned int>(hr));
        return false;
    }

    // Rasterizer state — no culling, solid fill
    D3D11_RASTERIZER_DESC rsDesc = {};
    rsDesc.FillMode = D3D11_FILL_SOLID;
    rsDesc.CullMode = D3D11_CULL_NONE;

    hr = device_->CreateRasterizerState(&rsDesc, &rasterizerState_);
    if (FAILED(hr)) {
        std::fprintf(stderr, "[Compositor] Failed to create rasterizer state, HR=0x%08X\n",
                     static_cast<unsigned int>(hr));
        return false;
    }

    // Depth-stencil state — depth disabled
    D3D11_DEPTH_STENCIL_DESC dsDesc = {};
    dsDesc.DepthEnable = FALSE;

    hr = device_->CreateDepthStencilState(&dsDesc, &depthStencilState_);
    if (FAILED(hr)) {
        std::fprintf(stderr, "[Compositor] Failed to create depth-stencil state, HR=0x%08X\n",
                     static_cast<unsigned int>(hr));
        return false;
    }

    return true;
}

// ===========================================================================
// Compositing
// ===========================================================================

void GridCompositor::compositeFrame(const std::vector<CellFrameRequest>& requests,
                                     RenderFrameCache& cache,
                                     int gridCols, int gridRows,
                                     float time,
                                     float gapScale)
{
    if (!initialized_) return;

    auto frameStart = std::chrono::high_resolution_clock::now();

    // Count layers for logging
    int chorusCount = 0, gridCount = 0, crashCount = 0;
    for (const auto& req : requests) {
        if (req.isChorus) ++chorusCount;
        else if (req.isCrash) ++crashCount;
        else ++gridCount;
    }

    std::fprintf(stderr, "[Compositor] Frame composite: %d chorus, %d grid cells, %d crash, %d total requests\n",
                 chorusCount, gridCount, crashCount, static_cast<int>(requests.size()));

    // ── Set up pipeline state ────────────────────────────────────────────────

    // Unbind the render target SRV to avoid D3D11 read/write hazard
    ID3D11ShaderResourceView* nullSRV = nullptr;
    deviceCtx_->PSSetShaderResources(0, 1, &nullSRV);

    // Set render target
    deviceCtx_->OMSetRenderTargets(1, renderTargetRTV_.GetAddressOf(), nullptr);

    // Clear to transparent black — areas with no content will be transparent.
    // The chorus layer provides the background; gaps without chorus encode
    // as black in H.264 (which has no alpha channel).
    const float clearColor[4] = { 0.0f, 0.0f, 0.0f, 0.0f };
    deviceCtx_->ClearRenderTargetView(renderTargetRTV_.Get(), clearColor);

    // Set viewport
    D3D11_VIEWPORT viewport = {};
    viewport.Width    = static_cast<float>(width_);
    viewport.Height   = static_cast<float>(height_);
    viewport.MinDepth = 0.0f;
    viewport.MaxDepth = 1.0f;
    deviceCtx_->RSSetViewports(1, &viewport);

    // Set pipeline state
    deviceCtx_->IASetInputLayout(inputLayout_.Get());
    deviceCtx_->IASetPrimitiveTopology(D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST);

    UINT stride = sizeof(QuadVertex);
    UINT offset = 0;
    deviceCtx_->IASetVertexBuffers(0, 1, vertexBuffer_.GetAddressOf(), &stride, &offset);
    deviceCtx_->IASetIndexBuffer(indexBuffer_.Get(), DXGI_FORMAT_R16_UINT, 0);

    deviceCtx_->VSSetShader(vertexShader_.Get(), nullptr, 0);
    deviceCtx_->PSSetShader(pixelShader_.Get(), nullptr, 0);
    deviceCtx_->PSSetSamplers(0, 1, samplerState_.GetAddressOf());
    deviceCtx_->PSSetConstantBuffers(0, 1, constantBuffer_.GetAddressOf());

    // Bind and update GlobalConstants at b1 (once per frame)
    deviceCtx_->VSSetConstantBuffers(1, 1, globalConstantBuffer_.GetAddressOf());
    deviceCtx_->PSSetConstantBuffers(1, 1, globalConstantBuffer_.GetAddressOf());
    {
        D3D11_MAPPED_SUBRESOURCE mapped;
        HRESULT hr = deviceCtx_->Map(globalConstantBuffer_.Get(), 0, D3D11_MAP_WRITE_DISCARD, 0, &mapped);
        if (SUCCEEDED(hr)) {
            GlobalConstants gc;
            gc.time         = time;
            gc.outputWidth  = static_cast<float>(width_);
            gc.outputHeight = static_cast<float>(height_);
            gc.padding      = 0.0f;
            std::memcpy(mapped.pData, &gc, sizeof(gc));
            deviceCtx_->Unmap(globalConstantBuffer_.Get(), 0);
        }
    }

    float blendFactor[4] = { 0, 0, 0, 0 };
    deviceCtx_->OMSetBlendState(blendState_.Get(), blendFactor, 0xFFFFFFFF);
    deviceCtx_->RSSetState(rasterizerState_.Get());
    deviceCtx_->OMSetDepthStencilState(depthStencilState_.Get(), 0);

    // ── Pass 1: Chorus (full-screen, behind everything) ──────────────────────
    for (const auto& req : requests) {
        if (!req.isChorus) continue;

        FrameCacheKey key;
        key.sourcePath = req.sourcePath;
        key.frameIndex = req.sourceFrameIndex;
        FrameCacheEntry* entry = cache.get(key);

        if (!entry || !entry->srv) {
            std::fprintf(stderr, "[Compositor] WARN: Skipping chorus — texture is null (cache miss?)\n");
            continue;
        }

        std::fprintf(stderr, "[Compositor] Chorus: '%s' frame=%lld opacity=%.2f\n",
                     req.sourcePath.c_str(), (long long)req.sourceFrameIndex, req.opacity);

        drawCell(entry->srv.Get(), 0.0f, 0.0f, 1.0f, 1.0f,
                 req.opacity, req.orientation, 0.0f);
    }

    // ── Pass 2: Grid cells (each at its grid position) ───────────────────────
    for (const auto& req : requests) {
        if (req.isChorus || req.isCrash) continue;

        FrameCacheKey key;
        key.sourcePath = req.sourcePath;
        key.frameIndex = req.sourceFrameIndex;
        FrameCacheEntry* entry = cache.get(key);

        if (!entry || !entry->srv) {
            std::fprintf(stderr, "[Compositor] WARN: Skipping cell [%d,%d] — texture is null (cache miss?)\n",
                         req.cellCol, req.cellRow);
            continue;
        }

        float rx, ry, rw, rh;
        gridCellToUV(req.cellCol, req.cellRow, req.spanX, req.spanY,
                     gridCols, gridRows, rx, ry, rw, rh);

        // Apply gap scale: shrink rect symmetrically, creating inter-cell padding
        float effectiveGap = (req.gapScaleOverride >= 0.0f) ? req.gapScaleOverride : gapScale;
        if (effectiveGap > 0.0f && !req.isChorus && !req.isCrash) {
            float sx = rw * effectiveGap * 0.5f;
            float sy = rh * effectiveGap * 0.5f;
            rx += sx;  ry += sy;
            rw -= sx * 2.0f;  rh -= sy * 2.0f;
        }

        // Apply bounce: offset (fraction of post-gap cell size) then scale-from-center
        if (!req.isChorus && !req.isCrash) {
            rx += req.bounceOffsetX * rw;
            ry += req.bounceOffsetY * rh;
            if (req.bounceScaleX != 1.0f || req.bounceScaleY != 1.0f) {
                float cx = rx + rw * 0.5f;
                float cy = ry + rh * 0.5f;
                rw *= req.bounceScaleX;
                rh *= req.bounceScaleY;
                rx = cx - rw * 0.5f;
                ry = cy - rh * 0.5f;
            }
        }

        std::fprintf(stderr, "[Compositor] Cell [%d,%d]: '%s' frame=%lld opacity=%.2f orient=%d\n",
                     req.cellCol, req.cellRow,
                     req.sourcePath.c_str(), (long long)req.sourceFrameIndex,
                     req.opacity, req.orientation);

        // Process visual effect chain (if any). The final orientation transform
        // is applied by the last drawCell() call — intermediate effect-chain
        // passes use orientation=0 (identity).
        ID3D11ShaderResourceView* cellSRV = entry->srv.Get();

        // Visual effect chain — skipped entirely when effectsBypass_ is set
        // (fast preview mode). Gap, bounce, corner-radius and opacity are
        // handled outside this block and are never bypassed.
        if (!effectsBypass_ && req.visualChain && !req.visualChain->empty()) {
            // Compute cell pixel dimensions from UV rect and output resolution
            int cellPixelW = std::max(1, static_cast<int>(rw * width_));
            int cellPixelH = std::max(1, static_cast<int>(rh * height_));

            ID3D11ShaderResourceView* processedSRV = processEffectChain(
                cellSRV, cellPixelW, cellPixelH,
                *req.visualChain, req, time, /*rtSlot=*/0);

            if (processedSRV != cellSRV) {
                // Chain was used — final orientation transform is applied by the
                // outer drawCell() once the effect-chain SRV is ready.
                cellSRV = processedSRV;

                // Restore main pipeline state after effect chain processing
                D3D11_VIEWPORT mainVP = {};
                mainVP.Width    = static_cast<float>(width_);
                mainVP.Height   = static_cast<float>(height_);
                mainVP.MinDepth = 0.0f;
                mainVP.MaxDepth = 1.0f;
                deviceCtx_->RSSetViewports(1, &mainVP);
                deviceCtx_->OMSetRenderTargets(1, renderTargetRTV_.GetAddressOf(), nullptr);
                deviceCtx_->PSSetShader(pixelShader_.Get(), nullptr, 0);
                deviceCtx_->PSSetConstantBuffers(0, 1, constantBuffer_.GetAddressOf());
                deviceCtx_->PSSetSamplers(0, 1, samplerState_.GetAddressOf());
            }
        }

        // Standalone ZPR pass — also skipped when effectsBypass_ is set.
        // Fires when animation has non-default values but ZPR is NOT already
        // in the visual effect chain (chainHadZpr prevents double-apply).
        // Uses rtSlot=1 to avoid aliasing with the main chain's slot-0 render targets.
        if (!effectsBypass_) {
            bool chainHadZpr = false;
            if (req.visualChain) {
                for (const auto& cfx : *req.visualChain) {
                    if (!cfx.bypassed && cfx.type == VisualEffect::Type::ZoomPanRotation)
                        { chainHadZpr = true; break; }
                }
            }
            bool zprNonDefault = (req.currentZoom != 1.0f || req.currentPanX != 0.0f ||
                                  req.currentPanY != 0.0f || req.currentRotDeg != 0.0f);
            if (zprNonDefault && !chainHadZpr) {
                int zpW = std::max(1, static_cast<int>(rw * width_));
                int zpH = std::max(1, static_cast<int>(rh * height_));
                VisualEffect standaloneZpr;
                standaloneZpr.type     = VisualEffect::Type::ZoomPanRotation;
                standaloneZpr.bypassed = false;
                std::vector<VisualEffect> zprChain = { standaloneZpr };
                ID3D11ShaderResourceView* zprSRV = processEffectChain(
                    cellSRV, zpW, zpH, zprChain, req, time, /*rtSlot=*/1);
                if (zprSRV != cellSRV) {
                    cellSRV = zprSRV;
                    // Outer drawCell() applies the orientation transform at final composite.
                    D3D11_VIEWPORT mainVP{};
                    mainVP.Width    = static_cast<float>(width_);
                    mainVP.Height   = static_cast<float>(height_);
                    mainVP.MaxDepth = 1.0f;
                    deviceCtx_->RSSetViewports(1, &mainVP);
                    deviceCtx_->OMSetRenderTargets(1, renderTargetRTV_.GetAddressOf(), nullptr);
                    deviceCtx_->PSSetShader(pixelShader_.Get(), nullptr, 0);
                    deviceCtx_->PSSetConstantBuffers(0, 1, constantBuffer_.GetAddressOf());
                    deviceCtx_->PSSetSamplers(0, 1, samplerState_.GetAddressOf());
                }
            }
        }

        // Ping-pong crossfade — also skipped when effectsBypass_ is set.
        // Blends primary cellSRV with secondary frame texture.
        // Uses rtSlot=2 to avoid aliasing with slot 0 (main chain) and slot 1 (ZPR).
        if (!effectsBypass_ && !req.isChorus && !req.isCrash && req.pingPongSecondaryFrame >= 0) {
            FrameCacheKey key2;
            key2.sourcePath = req.sourcePath;
            key2.frameIndex = req.pingPongSecondaryFrame;
            FrameCacheEntry* entry2 = cache.get(key2);
            if (entry2 && entry2->srv) {
                int ppW = std::max(1, static_cast<int>(rw * width_));
                int ppH = std::max(1, static_cast<int>(rh * height_));
                RTPool::RTPair& ppRTP = rtPool_.acquire(device_, ppW, ppH, /*rtSlot=*/2);
                if (ppRTP.rtvA && ppRTP.srvA) {
                    const float clear[4] = { 0.0f, 0.0f, 0.0f, 0.0f };
                    deviceCtx_->ClearRenderTargetView(ppRTP.rtvA.Get(), clear);

                    D3D11_VIEWPORT ppVP{};
                    ppVP.Width    = static_cast<float>(ppW);
                    ppVP.Height   = static_cast<float>(ppH);
                    ppVP.MaxDepth = 1.0f;
                    deviceCtx_->RSSetViewports(1, &ppVP);
                    deviceCtx_->OMSetRenderTargets(1, ppRTP.rtvA.GetAddressOf(), nullptr);
                    deviceCtx_->PSSetShader(pixelShader_.Get(), nullptr, 0);
                    deviceCtx_->PSSetConstantBuffers(0, 1, constantBuffer_.GetAddressOf());
                    deviceCtx_->PSSetSamplers(0, 1, samplerState_.GetAddressOf());

                    // Blit primary frame at full opacity. Intermediate effect-chain
                    // passes always use orientation=0 (identity); the final orientation
                    // transform is applied by the outer drawCell() call below.
                    {
                        D3D11_MAPPED_SUBRESOURCE mapped{};
                        if (SUCCEEDED(deviceCtx_->Map(constantBuffer_.Get(), 0,
                                                      D3D11_MAP_WRITE_DISCARD, 0, &mapped))) {
                            CellConstants cb{};
                            cb.cellRect[2]  = 1.0f; cb.cellRect[3] = 1.0f;
                            cb.opacity      = 1.0f;
                            cb.orientation  = 0;
                            cb.cornerRadius = 0.0f;
                            std::memcpy(mapped.pData, &cb, sizeof(cb));
                            deviceCtx_->Unmap(constantBuffer_.Get(), 0);
                        }
                    }
                    drawEffectPass(cellSRV);

                    // Blit secondary frame at blend opacity on top (alpha blending overlays it)
                    {
                        D3D11_MAPPED_SUBRESOURCE mapped{};
                        if (SUCCEEDED(deviceCtx_->Map(constantBuffer_.Get(), 0,
                                                      D3D11_MAP_WRITE_DISCARD, 0, &mapped))) {
                            CellConstants cb{};
                            cb.cellRect[2]  = 1.0f; cb.cellRect[3] = 1.0f;
                            cb.opacity      = req.pingPongBlendFactor;
                            cb.orientation  = 0;
                            cb.cornerRadius = 0.0f;
                            std::memcpy(mapped.pData, &cb, sizeof(cb));
                            deviceCtx_->Unmap(constantBuffer_.Get(), 0);
                        }
                    }
                    drawEffectPass(entry2->srv.Get());

                    // Unbind RT before reading as SRV
                    ID3D11RenderTargetView* nullRTV2 = nullptr;
                    deviceCtx_->OMSetRenderTargets(1, &nullRTV2, nullptr);
                    cellSRV = ppRTP.srvA.Get();
                    // Outer drawCell() applies the orientation transform at final composite.

                    // Restore main pipeline state
                    D3D11_VIEWPORT mainVP2{};
                    mainVP2.Width    = static_cast<float>(width_);
                    mainVP2.Height   = static_cast<float>(height_);
                    mainVP2.MaxDepth = 1.0f;
                    deviceCtx_->RSSetViewports(1, &mainVP2);
                    deviceCtx_->OMSetRenderTargets(1, renderTargetRTV_.GetAddressOf(), nullptr);
                    deviceCtx_->PSSetShader(pixelShader_.Get(), nullptr, 0);
                    deviceCtx_->PSSetConstantBuffers(0, 1, constantBuffer_.GetAddressOf());
                    deviceCtx_->PSSetSamplers(0, 1, samplerState_.GetAddressOf());
                }
            }
        }

        drawCell(cellSRV, rx, ry, rw, rh,
                 req.opacity, req.orientation, req.cornerRadius);
    }

    // ── Pass 3: Crash overlay (full-screen, on top) ──────────────────────────
    for (const auto& req : requests) {
        if (!req.isCrash) continue;

        FrameCacheKey key;
        key.sourcePath = req.sourcePath;
        key.frameIndex = req.sourceFrameIndex;
        FrameCacheEntry* entry = cache.get(key);

        if (!entry || !entry->srv) {
            std::fprintf(stderr, "[Compositor] WARN: Skipping crash — texture is null (cache miss?)\n");
            continue;
        }

        std::fprintf(stderr, "[Compositor] Crash: '%s' frame=%lld opacity=%.2f\n",
                     req.sourcePath.c_str(), (long long)req.sourceFrameIndex, req.opacity);

        drawCell(entry->srv.Get(), 0.0f, 0.0f, 1.0f, 1.0f,
                 req.opacity, req.orientation, 0.0f);
    }

    // Unbind render target to allow subsequent SRV reads
    ID3D11RenderTargetView* nullRTV = nullptr;
    deviceCtx_->OMSetRenderTargets(1, &nullRTV, nullptr);

    auto frameEnd = std::chrono::high_resolution_clock::now();
    double ms = std::chrono::duration<double, std::milli>(frameEnd - frameStart).count();
    std::fprintf(stderr, "[Compositor] Frame composited in %.2fms\n", ms);
}

// ===========================================================================
// Draw one cell
// ===========================================================================

void GridCompositor::drawCell(ID3D11ShaderResourceView* srv,
                               float rectX, float rectY, float rectW, float rectH,
                               float opacity, int orientation, float cornerRadius)
{
    // Update constant buffer
    D3D11_MAPPED_SUBRESOURCE mapped;
    HRESULT hr = deviceCtx_->Map(constantBuffer_.Get(), 0, D3D11_MAP_WRITE_DISCARD, 0, &mapped);
    if (FAILED(hr)) return;

    CellConstants cb{};
    cb.cellRect[0]  = rectX;
    cb.cellRect[1]  = rectY;
    cb.cellRect[2]  = rectW;
    cb.cellRect[3]  = rectH;
    cb.opacity      = opacity;
    cb.orientation  = orientation;
    cb.cornerRadius = cornerRadius;

    std::memcpy(mapped.pData, &cb, sizeof(cb));
    deviceCtx_->Unmap(constantBuffer_.Get(), 0);

    // Bind texture
    deviceCtx_->PSSetShaderResources(0, 1, &srv);

    // Draw the quad (6 indices)
    deviceCtx_->DrawIndexed(6, 0, 0);
}

// ===========================================================================
// GPU→CPU readback
// ===========================================================================

ReadbackBuffer GridCompositor::readback()
{
    ReadbackBuffer buf;
    if (!initialized_) return buf;

    auto start = std::chrono::high_resolution_clock::now();

    // Two-texture staging ring — avoids AMD WDDM timing failures.
    //
    // Calling CopyResource(staging, rt) + Map(staging, READ, 0) on the SAME
    // staging texture in back-to-back frames causes Map to return
    // DXGI_ERROR_WAS_STILL_DRAWING on AMD even without DO_NOT_WAIT, because
    // the previous copy hasn't fully retired by the time the next one is issued.
    // NVIDIA tolerates this; AMD doesn't.
    //
    // Fix: alternate between two staging textures.
    //   Frame N:   CopyResource → staging[N%2]     (submit this frame's copy)
    //              Map           ← staging[(N-1)%2] (read previous frame's copy)
    // The previous staging's copy was submitted a full frame period ago, so the
    // GPU has had ample time (≥33 ms at 30 fps) to complete it.
    const uint64_t writeIdx = readbackFrameCount_ % 2;
    const uint64_t readIdx  = 1 - writeIdx;  // == (readbackFrameCount_ - 1) % 2

    // Submit copy into this frame's staging slot
    deviceCtx_->CopyResource(stagingTextures_[writeIdx].Get(), renderTarget_.Get());

    if (readbackFrameCount_ == 0) {
        // First call: no previous staging to read yet — ring is priming.
        // Return invalid; next call will successfully Map staging[0].
        ++readbackFrameCount_;
        std::fprintf(stderr, "[Compositor] Readback ring priming (frame 0 skip)\n");
        return buf;
    }

    // Map the PREVIOUS frame's staging texture
    D3D11_MAPPED_SUBRESOURCE mapped;
    HRESULT hr = deviceCtx_->Map(stagingTextures_[readIdx].Get(), 0,
                                  D3D11_MAP_READ, 0, &mapped);
    ++readbackFrameCount_;

    if (FAILED(hr)) {
        lastReadbackHR_ = hr;
        D3D11_TEXTURE2D_DESC sdesc{};
        stagingTextures_[readIdx]->GetDesc(&sdesc);
        std::fprintf(stderr,
            "[Compositor] Readback Map FAILED: HR=0x%08X (%s) "
            "staging[%llu] %ux%u fmt=%u usage=%u bind=0x%X cpu=0x%X rowPitchExpected=%u\n",
            static_cast<unsigned int>(hr), hrText(hr),
            static_cast<unsigned long long>(readIdx),
            sdesc.Width, sdesc.Height,
            static_cast<unsigned>(sdesc.Format),
            static_cast<unsigned>(sdesc.Usage),
            sdesc.BindFlags, sdesc.CPUAccessFlags,
            sdesc.Width * 4u);
        return buf;
    }

    lastReadbackHR_ = S_OK;
    buf.width  = width_;
    buf.height = height_;
    buf.stride = width_ * 4;
    buf.pixels.resize(static_cast<size_t>(buf.stride) * height_);

    // Copy row by row (staging pitch may differ from our tightly-packed stride)
    const uint8_t* src = static_cast<const uint8_t*>(mapped.pData);
    for (int y = 0; y < height_; ++y) {
        std::memcpy(buf.pixels.data() + y * buf.stride,
                    src + y * mapped.RowPitch,
                    static_cast<size_t>(buf.stride));
    }

    deviceCtx_->Unmap(stagingTextures_[readIdx].Get(), 0);
    buf.valid = true;

    auto end = std::chrono::high_resolution_clock::now();
    double ms = std::chrono::duration<double, std::milli>(end - start).count();
    std::fprintf(stderr, "[Compositor] GPU readback: %dx%d in %.2fms\n",
                 width_, height_, ms);

    return buf;
}

// ===========================================================================
// Grid cell → UV mapping
// ===========================================================================

void GridCompositor::gridCellToUV(int cellCol, int cellRow, int spanX, int spanY,
                                   int gridCols, int gridRows,
                                   float& outX, float& outY, float& outW, float& outH)
{
    // Fine-grid: an NxM grid has (N*kGridSubUnitsPerColumn) x
    // (M*kGridSubUnitsPerRow) sub-grid positions. cellCol/cellRow are in
    // sub-grid coords; spanX/spanY are in sub-grid units (kGridSubUnitsPerColumn
    // = full column).
    const float subCellW = 1.0f / (gridCols * static_cast<float>(kGridSubUnitsPerColumn));
    const float subCellH = 1.0f / (gridRows * static_cast<float>(kGridSubUnitsPerRow));

    outX = cellCol * subCellW;
    outY = cellRow * subCellH;
    outW = spanX  * subCellW;
    outH = spanY  * subCellH;
}

// ===========================================================================
// RTPool — render target pairs for ping-pong effect processing
// ===========================================================================

RTPool::RTPair& RTPool::acquire(ID3D11Device* device, int width, int height, int slot)
{
    // Key encodes slot, width, height to prevent aliasing between independent passes
    uint64_t key = (static_cast<uint64_t>(slot) << 48)
                 | (static_cast<uint64_t>(width & 0xFFFF) << 32)
                 | static_cast<uint64_t>(height & 0xFFFFFFFF);

    auto it = pairs.find(key);
    if (it != pairs.end() && it->second.width == width && it->second.height == height) {
        return it->second;
    }

    // Create a new pair
    RTPair pair;
    pair.width  = width;
    pair.height = height;

    D3D11_TEXTURE2D_DESC desc = {};
    desc.Width            = static_cast<UINT>(width);
    desc.Height           = static_cast<UINT>(height);
    desc.MipLevels        = 1;
    desc.ArraySize        = 1;
    desc.Format           = DXGI_FORMAT_R8G8B8A8_UNORM;
    desc.SampleDesc.Count = 1;
    desc.Usage            = D3D11_USAGE_DEFAULT;
    desc.BindFlags        = D3D11_BIND_SHADER_RESOURCE | D3D11_BIND_RENDER_TARGET;

    HRESULT hr = device->CreateTexture2D(&desc, nullptr, &pair.texA);
    if (FAILED(hr)) {
        std::fprintf(stderr, "[RTPool] Failed to create texA %dx%d slot=%d, HR=0x%08X\n",
                     width, height, slot, static_cast<unsigned int>(hr));
    }
    hr = device->CreateTexture2D(&desc, nullptr, &pair.texB);
    if (FAILED(hr)) {
        std::fprintf(stderr, "[RTPool] Failed to create texB %dx%d slot=%d, HR=0x%08X\n",
                     width, height, slot, static_cast<unsigned int>(hr));
    }

    device->CreateRenderTargetView(pair.texA.Get(), nullptr, &pair.rtvA);
    device->CreateRenderTargetView(pair.texB.Get(), nullptr, &pair.rtvB);
    device->CreateShaderResourceView(pair.texA.Get(), nullptr, &pair.srvA);
    device->CreateShaderResourceView(pair.texB.Get(), nullptr, &pair.srvB);

    std::fprintf(stderr, "[RTPool] Created RT pair %dx%d slot=%d\n", width, height, slot);

    pairs[key] = std::move(pair);
    return pairs[key];
}

void RTPool::clear()
{
    pairs.clear();
}

// ===========================================================================
// EffectShaderCache — compiled effect pixel shaders
// ===========================================================================

static bool createEffectCB(ID3D11Device* device, UINT sizeBytes,
                           Microsoft::WRL::ComPtr<ID3D11Buffer>& outBuf,
                           const char* name)
{
    // Round up to 16-byte alignment (D3D11 requirement)
    UINT aligned = (sizeBytes + 15) & ~15u;

    D3D11_BUFFER_DESC desc = {};
    desc.Usage          = D3D11_USAGE_DYNAMIC;
    desc.ByteWidth      = aligned;
    desc.BindFlags      = D3D11_BIND_CONSTANT_BUFFER;
    desc.CPUAccessFlags = D3D11_CPU_ACCESS_WRITE;

    HRESULT hr = device->CreateBuffer(&desc, nullptr, &outBuf);
    if (FAILED(hr)) {
        std::fprintf(stderr, "[EffectShaders] Failed to create CB '%s' (%u bytes), HR=0x%08X\n",
                     name, aligned, static_cast<unsigned int>(hr));
        return false;
    }
    return true;
}

bool EffectShaderCache::init(ID3D11Device* device)
{
    if (!device) return false;

    HRESULT hr;

    // Create pixel shaders from precompiled bytecode
    hr = device->CreatePixelShader(g_FX_DesaturationPS, sizeof(g_FX_DesaturationPS),
                                   nullptr, &desaturationPS);
    if (FAILED(hr)) {
        std::fprintf(stderr, "[EffectShaders] Failed: Desaturation PS\n");
        return false;
    }

    hr = device->CreatePixelShader(g_FX_TintPS, sizeof(g_FX_TintPS),
                                   nullptr, &tintPS);
    if (FAILED(hr)) {
        std::fprintf(stderr, "[EffectShaders] Failed: Tint PS\n");
        return false;
    }

    hr = device->CreatePixelShader(g_FX_BrightnessContrastPS, sizeof(g_FX_BrightnessContrastPS),
                                   nullptr, &brightnessContrastPS);
    if (FAILED(hr)) {
        std::fprintf(stderr, "[EffectShaders] Failed: BrightnessContrast PS\n");
        return false;
    }

    hr = device->CreatePixelShader(g_FX_TVSimulatorPS, sizeof(g_FX_TVSimulatorPS),
                                   nullptr, &tvSimulatorPS);
    if (FAILED(hr)) {
        std::fprintf(stderr, "[EffectShaders] Failed: TVSimulator PS\n");
        return false;
    }

    hr = device->CreatePixelShader(g_FX_ZoomPanRotationPS, sizeof(g_FX_ZoomPanRotationPS),
                                   nullptr, &zoomPanRotPS);
    if (FAILED(hr)) {
        std::fprintf(stderr, "[EffectShaders] Failed: ZoomPanRotation PS\n");
        return false;
    }

    // Create per-effect constant buffers at b2
    if (!createEffectCB(device, 16, desatCB,      "Desaturation"))    return false;
    if (!createEffectCB(device, 32, tintCB,        "Tint"))            return false;
    if (!createEffectCB(device, 16, brightContCB,  "BrightnessContrast")) return false;
    if (!createEffectCB(device, 32, tvSimCB,       "TVSimulator"))     return false;
    if (!createEffectCB(device, 16, zoomPanRotCB,  "ZoomPanRotation")) return false;

    initialized = true;
    std::fprintf(stderr, "[EffectShaders] All 5 effect shaders + CBs created (placeholders)\n");
    return true;
}

void EffectShaderCache::shutdown()
{
    desaturationPS.Reset();
    tintPS.Reset();
    brightnessContrastPS.Reset();
    tvSimulatorPS.Reset();
    zoomPanRotPS.Reset();
    desatCB.Reset();
    tintCB.Reset();
    brightContCB.Reset();
    tvSimCB.Reset();
    zoomPanRotCB.Reset();
    initialized = false;
}

// ===========================================================================
// blitFullscreen — blit source texture into current RT with flip mode
// ===========================================================================

void GridCompositor::blitFullscreen(ID3D11ShaderResourceView* srv, int orientation)
{
    // Use the main GridComposite pixel shader with cellRect covering full UV [0,1]
    deviceCtx_->PSSetShader(pixelShader_.Get(), nullptr, 0);
    drawCell(srv, 0.0f, 0.0f, 1.0f, 1.0f, 1.0f, orientation, 0.0f);
}

// ===========================================================================
// drawEffectPass — draw a fullscreen pass with the currently set PS
// ===========================================================================

void GridCompositor::drawEffectPass(ID3D11ShaderResourceView* srv)
{
    // Bind texture
    deviceCtx_->PSSetShaderResources(0, 1, &srv);

    // Draw the fullscreen quad
    deviceCtx_->DrawIndexed(6, 0, 0);
}

// ===========================================================================
// processEffectChain — apply visual effect chain via ping-pong RTs
// ===========================================================================

ID3D11ShaderResourceView* GridCompositor::processEffectChain(
    ID3D11ShaderResourceView* sourceSRV,
    int cellWidth, int cellHeight,
    const std::vector<VisualEffect>& chain,
    const CellFrameRequest& req,
    float time,
    int rtSlot)
{
    if (!initialized_ || !effectShaders_.initialized) return sourceSRV;

    // Fast path: empty chain or all bypassed → zero GPU cost
    bool anyActive = false;
    for (const auto& fx : chain) {
        if (!fx.bypassed) { anyActive = true; break; }
    }
    if (!anyActive) return sourceSRV;

    if (cellWidth <= 0 || cellHeight <= 0) return sourceSRV;

#ifdef XLETH_DEBUG
    std::fprintf(stderr, "[VisualFX] Cell track=%d: chain has %zu effects, processing at %dx%d, slot=%d\n",
                 req.trackId, chain.size(), cellWidth, cellHeight, rtSlot);
#endif

    // Get RT pair for this cell size + slot
    RTPool::RTPair& rtp = rtPool_.acquire(device_, cellWidth, cellHeight, rtSlot);
    if (!rtp.rtvA || !rtp.rtvB || !rtp.srvA || !rtp.srvB) return sourceSRV;

    // Save the main output render target — we'll restore it after processing
    // (compositeFrame re-binds before drawCell anyway, but be safe)

    // Set up viewport for cell-sized RT
    D3D11_VIEWPORT cellVP = {};
    cellVP.Width    = static_cast<float>(cellWidth);
    cellVP.Height   = static_cast<float>(cellHeight);
    cellVP.MinDepth = 0.0f;
    cellVP.MaxDepth = 1.0f;
    deviceCtx_->RSSetViewports(1, &cellVP);

    // Step 1: Blit sourceSRV into RT_A (plain copy — flip is applied at final drawCell)
    const float clearColor[4] = { 0.0f, 0.0f, 0.0f, 0.0f };
    deviceCtx_->ClearRenderTargetView(rtp.rtvA.Get(), clearColor);
    deviceCtx_->OMSetRenderTargets(1, rtp.rtvA.GetAddressOf(), nullptr);

    // Use the main GridComposite PS for the blit
    deviceCtx_->PSSetShader(pixelShader_.Get(), nullptr, 0);
    deviceCtx_->PSSetConstantBuffers(0, 1, constantBuffer_.GetAddressOf());

    // Set up CellConstants for a fullscreen blit (identity orientation —
    // any flip is applied later by the outer drawCell() at the final composite).
    {
        D3D11_MAPPED_SUBRESOURCE mapped;
        HRESULT hr = deviceCtx_->Map(constantBuffer_.Get(), 0, D3D11_MAP_WRITE_DISCARD, 0, &mapped);
        if (SUCCEEDED(hr)) {
            CellConstants cb{};
            cb.cellRect[0]  = 0.0f;
            cb.cellRect[1]  = 0.0f;
            cb.cellRect[2]  = 1.0f;
            cb.cellRect[3]  = 1.0f;
            cb.opacity      = 1.0f;
            cb.orientation  = 0;
            cb.cornerRadius = 0.0f;
            std::memcpy(mapped.pData, &cb, sizeof(cb));
            deviceCtx_->Unmap(constantBuffer_.Get(), 0);
        }
    }
    drawEffectPass(sourceSRV);

    // Unbind RT_A from output before we read from it
    ID3D11RenderTargetView* nullRTV = nullptr;
    deviceCtx_->OMSetRenderTargets(1, &nullRTV, nullptr);

    // Step 2: Ping-pong through effect chain
    // After blit: RT_A has the flipped source. Start reading from srvA.
    ID3D11ShaderResourceView*  currentSrc = rtp.srvA.Get();
    ID3D11RenderTargetView*    currentDst = rtp.rtvB.Get();
    ID3D11ShaderResourceView*  nextSrc    = rtp.srvB.Get();
    ID3D11RenderTargetView*    nextDst    = rtp.rtvA.Get();

    for (const auto& fx : chain) {
        if (fx.bypassed) continue;

        // Select the effect's pixel shader and CB
        ID3D11PixelShader* fxPS = nullptr;
        ID3D11Buffer*      fxCB = nullptr;

        switch (fx.type) {
            case VisualEffect::Type::Desaturation:
                fxPS = effectShaders_.desaturationPS.Get();
                fxCB = effectShaders_.desatCB.Get();
                break;
            case VisualEffect::Type::Tint:
                fxPS = effectShaders_.tintPS.Get();
                fxCB = effectShaders_.tintCB.Get();
                break;
            case VisualEffect::Type::BrightnessContrast:
                fxPS = effectShaders_.brightnessContrastPS.Get();
                fxCB = effectShaders_.brightContCB.Get();
                break;
            case VisualEffect::Type::TVSimulator:
                fxPS = effectShaders_.tvSimulatorPS.Get();
                fxCB = effectShaders_.tvSimCB.Get();
                break;
            case VisualEffect::Type::ZoomPanRotation: {
                // Upload animated values from req (or static params[] fallback).
                // Uses b0 (not b2), so handle CB explicitly and set fxCB=nullptr
                // to skip the generic memcpy/PSSetConstantBuffers(2,...) path.
                bool animActive = (req.currentZoom   != 1.0f || req.currentPanX != 0.0f ||
                                   req.currentPanY   != 0.0f || req.currentRotDeg != 0.0f);
                struct { float zoom, panX, panY, rotRad; } zprCBData;
                if (animActive) {
                    zprCBData.zoom   = req.currentZoom;
                    zprCBData.panX   = req.currentPanX;
                    zprCBData.panY   = req.currentPanY;
                    zprCBData.rotRad = req.currentRotDeg * (3.14159265f / 180.0f);
                } else {
                    zprCBData.zoom   = (fx.params[1] > 0.001f) ? fx.params[1] : 1.0f; // targetZoom
                    zprCBData.panX   = fx.params[4];                                   // targetPanX
                    zprCBData.panY   = fx.params[5];                                   // targetPanY
                    zprCBData.rotRad = fx.params[7] * (3.14159265f / 180.0f);         // targetRotDeg→rad
                }
                D3D11_MAPPED_SUBRESOURCE zprMapped{};
                if (SUCCEEDED(deviceCtx_->Map(effectShaders_.zoomPanRotCB.Get(), 0,
                                              D3D11_MAP_WRITE_DISCARD, 0, &zprMapped))) {
                    std::memcpy(zprMapped.pData, &zprCBData, sizeof(zprCBData));
                    deviceCtx_->Unmap(effectShaders_.zoomPanRotCB.Get(), 0);
                }
                auto* zprCBRaw = effectShaders_.zoomPanRotCB.Get();
                deviceCtx_->PSSetConstantBuffers(0, 1, &zprCBRaw);
                fxPS = effectShaders_.zoomPanRotPS.Get();
                fxCB = nullptr;  // skip generic memcpy / PSSetConstantBuffers(2,...) path
                break;
            }
        }

        if (!fxPS) continue;

        // Update the effect's CB with params from VisualEffect::params[]
        // (Placeholder shaders ignore the CB — actual param passing comes in later prompts)
        if (fxCB) {
            D3D11_MAPPED_SUBRESOURCE mapped;
            HRESULT hr = deviceCtx_->Map(fxCB, 0, D3D11_MAP_WRITE_DISCARD, 0, &mapped);
            if (SUCCEEDED(hr)) {
                // Copy params (up to 16 floats = 64 bytes, but CB may be smaller)
                // The CB size was set at creation; just copy what fits
                D3D11_BUFFER_DESC cbDesc;
                fxCB->GetDesc(&cbDesc);
                UINT copySize = std::min(static_cast<UINT>(sizeof(fx.params)), cbDesc.ByteWidth);
                std::memcpy(mapped.pData, fx.params, copySize);
                deviceCtx_->Unmap(fxCB, 0);
            }
            deviceCtx_->PSSetConstantBuffers(2, 1, &fxCB);
        }

        // Set effect PS and draw into currentDst
        deviceCtx_->PSSetShader(fxPS, nullptr, 0);
        deviceCtx_->ClearRenderTargetView(currentDst, clearColor);
        deviceCtx_->OMSetRenderTargets(1, &currentDst, nullptr);
        drawEffectPass(currentSrc);

        // Unbind RTV before next pass reads from it
        deviceCtx_->OMSetRenderTargets(1, &nullRTV, nullptr);

        // Swap src/dst for next pass
        std::swap(currentSrc, nextSrc);
        std::swap(currentDst, nextDst);
    }

    // Self-clean: unbind SRV at t0 and RTV to prevent hazards
    ID3D11ShaderResourceView* nullSRV = nullptr;
    deviceCtx_->PSSetShaderResources(0, 1, &nullSRV);
    deviceCtx_->OMSetRenderTargets(1, &nullRTV, nullptr);

    // currentSrc now points to the SRV of whichever RT has the final output
    return currentSrc;
}
