#include "GridCompositor.h"

#include <algorithm>
#include <cassert>
#include <cstdio>
#include <cstring>

// Precompiled shader bytecode (generated by fxc.exe from GridComposite.hlsl)
#include "shaders/GridCompositeVS.h"
#include "shaders/GridCompositePS.h"

// ---------------------------------------------------------------------------
// Vertex layout for the fullscreen quad
// ---------------------------------------------------------------------------
struct QuadVertex {
    float x, y;   // NDC position
    float u, v;   // UV
};

// ===========================================================================
// Lifecycle
// ===========================================================================

GridCompositor::GridCompositor() = default;

GridCompositor::~GridCompositor()
{
    shutdown();
}

bool GridCompositor::init(ID3D11Device* device, ID3D11DeviceContext* deviceCtx,
                           int width, int height)
{
    if (!device || !deviceCtx || width <= 0 || height <= 0) {
        std::fprintf(stderr, "[Compositor] Init failed: invalid parameters\n");
        return false;
    }

    shutdown();  // clean up any previous state

    device_    = device;
    deviceCtx_ = deviceCtx;
    width_     = width;
    height_    = height;

    if (!createRenderTarget())   return false;
    if (!createStagingTexture()) return false;
    if (!createShaders())        return false;
    if (!createGeometry())       return false;
    if (!createPipelineState())  return false;

    initialized_ = true;
    std::fprintf(stderr, "[Compositor] Init: %dx%d render target, BGRA, blend=SRC_ALPHA/INV_SRC_ALPHA\n",
                 width_, height_);
    return true;
}

void GridCompositor::shutdown()
{
    renderTarget_.Reset();
    renderTargetRTV_.Reset();
    renderTargetSRV_.Reset();
    stagingTexture_.Reset();
    vertexShader_.Reset();
    pixelShader_.Reset();
    inputLayout_.Reset();
    vertexBuffer_.Reset();
    indexBuffer_.Reset();
    blendState_.Reset();
    samplerState_.Reset();
    constantBuffer_.Reset();
    rasterizerState_.Reset();
    depthStencilState_.Reset();

    device_      = nullptr;
    deviceCtx_   = nullptr;
    width_       = 0;
    height_      = 0;
    initialized_ = false;
}

// ===========================================================================
// Resource creation
// ===========================================================================

bool GridCompositor::createRenderTarget()
{
    D3D11_TEXTURE2D_DESC desc = {};
    desc.Width            = static_cast<UINT>(width_);
    desc.Height           = static_cast<UINT>(height_);
    desc.MipLevels        = 1;
    desc.ArraySize        = 1;
    desc.Format           = DXGI_FORMAT_B8G8R8A8_UNORM;
    desc.SampleDesc.Count = 1;
    desc.Usage            = D3D11_USAGE_DEFAULT;
    desc.BindFlags        = D3D11_BIND_RENDER_TARGET | D3D11_BIND_SHADER_RESOURCE;

    HRESULT hr = device_->CreateTexture2D(&desc, nullptr, &renderTarget_);
    if (FAILED(hr)) {
        std::fprintf(stderr, "[Compositor] Failed to create render target, HR=0x%08X\n",
                     static_cast<unsigned int>(hr));
        return false;
    }

    hr = device_->CreateRenderTargetView(renderTarget_.Get(), nullptr, &renderTargetRTV_);
    if (FAILED(hr)) {
        std::fprintf(stderr, "[Compositor] Failed to create RTV, HR=0x%08X\n",
                     static_cast<unsigned int>(hr));
        return false;
    }

    hr = device_->CreateShaderResourceView(renderTarget_.Get(), nullptr, &renderTargetSRV_);
    if (FAILED(hr)) {
        std::fprintf(stderr, "[Compositor] Failed to create RT SRV, HR=0x%08X\n",
                     static_cast<unsigned int>(hr));
        return false;
    }

    return true;
}

bool GridCompositor::createStagingTexture()
{
    D3D11_TEXTURE2D_DESC desc = {};
    desc.Width            = static_cast<UINT>(width_);
    desc.Height           = static_cast<UINT>(height_);
    desc.MipLevels        = 1;
    desc.ArraySize        = 1;
    desc.Format           = DXGI_FORMAT_B8G8R8A8_UNORM;
    desc.SampleDesc.Count = 1;
    desc.Usage            = D3D11_USAGE_STAGING;
    desc.CPUAccessFlags   = D3D11_CPU_ACCESS_READ;

    HRESULT hr = device_->CreateTexture2D(&desc, nullptr, &stagingTexture_);
    if (FAILED(hr)) {
        std::fprintf(stderr, "[Compositor] Failed to create staging texture, HR=0x%08X\n",
                     static_cast<unsigned int>(hr));
        return false;
    }

    return true;
}

bool GridCompositor::createShaders()
{
    // Vertex shader from precompiled bytecode
    HRESULT hr = device_->CreateVertexShader(
        g_GridCompositeVS, sizeof(g_GridCompositeVS), nullptr, &vertexShader_);
    if (FAILED(hr)) {
        std::fprintf(stderr, "[Compositor] Shader compiled: vertex=FAIL pixel=?\n");
        return false;
    }

    // Pixel shader from precompiled bytecode
    hr = device_->CreatePixelShader(
        g_GridCompositePS, sizeof(g_GridCompositePS), nullptr, &pixelShader_);
    if (FAILED(hr)) {
        std::fprintf(stderr, "[Compositor] Shader compiled: vertex=OK pixel=FAIL\n");
        return false;
    }

    // Input layout matching VSInput: POSITION (float2) + TEXCOORD0 (float2)
    D3D11_INPUT_ELEMENT_DESC layoutDesc[] = {
        { "POSITION", 0, DXGI_FORMAT_R32G32_FLOAT, 0, 0,
          D3D11_INPUT_PER_VERTEX_DATA, 0 },
        { "TEXCOORD", 0, DXGI_FORMAT_R32G32_FLOAT, 0, 8,
          D3D11_INPUT_PER_VERTEX_DATA, 0 },
    };
    hr = device_->CreateInputLayout(
        layoutDesc, 2,
        g_GridCompositeVS, sizeof(g_GridCompositeVS),
        &inputLayout_);
    if (FAILED(hr)) {
        std::fprintf(stderr, "[Compositor] Failed to create input layout, HR=0x%08X\n",
                     static_cast<unsigned int>(hr));
        return false;
    }

    std::fprintf(stderr, "[Compositor] Shader compiled: vertex=OK pixel=OK\n");
    return true;
}

bool GridCompositor::createGeometry()
{
    // Fullscreen quad: 4 vertices covering NDC (-1,-1) to (1,1)
    // UV: (0,0) at top-left, (1,1) at bottom-right
    // Note: D3D11 NDC has Y+ up, UV has V+ down → flip V in vertex data
    QuadVertex vertices[] = {
        { -1.0f,  1.0f,  0.0f, 0.0f },  // top-left
        {  1.0f,  1.0f,  1.0f, 0.0f },  // top-right
        {  1.0f, -1.0f,  1.0f, 1.0f },  // bottom-right
        { -1.0f, -1.0f,  0.0f, 1.0f },  // bottom-left
    };

    D3D11_BUFFER_DESC vbDesc = {};
    vbDesc.Usage          = D3D11_USAGE_IMMUTABLE;
    vbDesc.ByteWidth      = sizeof(vertices);
    vbDesc.BindFlags      = D3D11_BIND_VERTEX_BUFFER;

    D3D11_SUBRESOURCE_DATA vbData = {};
    vbData.pSysMem = vertices;

    HRESULT hr = device_->CreateBuffer(&vbDesc, &vbData, &vertexBuffer_);
    if (FAILED(hr)) {
        std::fprintf(stderr, "[Compositor] Failed to create vertex buffer, HR=0x%08X\n",
                     static_cast<unsigned int>(hr));
        return false;
    }

    // Index buffer: 2 triangles (6 indices)
    uint16_t indices[] = { 0, 1, 2,  0, 2, 3 };

    D3D11_BUFFER_DESC ibDesc = {};
    ibDesc.Usage          = D3D11_USAGE_IMMUTABLE;
    ibDesc.ByteWidth      = sizeof(indices);
    ibDesc.BindFlags      = D3D11_BIND_INDEX_BUFFER;

    D3D11_SUBRESOURCE_DATA ibData = {};
    ibData.pSysMem = indices;

    hr = device_->CreateBuffer(&ibDesc, &ibData, &indexBuffer_);
    if (FAILED(hr)) {
        std::fprintf(stderr, "[Compositor] Failed to create index buffer, HR=0x%08X\n",
                     static_cast<unsigned int>(hr));
        return false;
    }

    return true;
}

bool GridCompositor::createPipelineState()
{
    // Alpha blend state: SRC_ALPHA / INV_SRC_ALPHA
    D3D11_BLEND_DESC blendDesc = {};
    blendDesc.RenderTarget[0].BlendEnable           = TRUE;
    blendDesc.RenderTarget[0].SrcBlend               = D3D11_BLEND_SRC_ALPHA;
    blendDesc.RenderTarget[0].DestBlend              = D3D11_BLEND_INV_SRC_ALPHA;
    blendDesc.RenderTarget[0].BlendOp                = D3D11_BLEND_OP_ADD;
    blendDesc.RenderTarget[0].SrcBlendAlpha          = D3D11_BLEND_ONE;
    blendDesc.RenderTarget[0].DestBlendAlpha         = D3D11_BLEND_INV_SRC_ALPHA;
    blendDesc.RenderTarget[0].BlendOpAlpha           = D3D11_BLEND_OP_ADD;
    blendDesc.RenderTarget[0].RenderTargetWriteMask  = D3D11_COLOR_WRITE_ENABLE_ALL;

    HRESULT hr = device_->CreateBlendState(&blendDesc, &blendState_);
    if (FAILED(hr)) {
        std::fprintf(stderr, "[Compositor] Failed to create blend state, HR=0x%08X\n",
                     static_cast<unsigned int>(hr));
        return false;
    }

    // Linear sampler with clamp
    D3D11_SAMPLER_DESC samplerDesc = {};
    samplerDesc.Filter         = D3D11_FILTER_MIN_MAG_MIP_LINEAR;
    samplerDesc.AddressU       = D3D11_TEXTURE_ADDRESS_CLAMP;
    samplerDesc.AddressV       = D3D11_TEXTURE_ADDRESS_CLAMP;
    samplerDesc.AddressW       = D3D11_TEXTURE_ADDRESS_CLAMP;
    samplerDesc.ComparisonFunc = D3D11_COMPARISON_NEVER;
    samplerDesc.MaxLOD         = D3D11_FLOAT32_MAX;

    hr = device_->CreateSamplerState(&samplerDesc, &samplerState_);
    if (FAILED(hr)) {
        std::fprintf(stderr, "[Compositor] Failed to create sampler, HR=0x%08X\n",
                     static_cast<unsigned int>(hr));
        return false;
    }

    // Constant buffer (CellConstants, 32 bytes)
    D3D11_BUFFER_DESC cbDesc = {};
    cbDesc.Usage          = D3D11_USAGE_DYNAMIC;
    cbDesc.ByteWidth      = sizeof(CellConstants);
    cbDesc.BindFlags      = D3D11_BIND_CONSTANT_BUFFER;
    cbDesc.CPUAccessFlags = D3D11_CPU_ACCESS_WRITE;

    hr = device_->CreateBuffer(&cbDesc, nullptr, &constantBuffer_);
    if (FAILED(hr)) {
        std::fprintf(stderr, "[Compositor] Failed to create constant buffer, HR=0x%08X\n",
                     static_cast<unsigned int>(hr));
        return false;
    }

    // Rasterizer state — no culling, solid fill
    D3D11_RASTERIZER_DESC rsDesc = {};
    rsDesc.FillMode = D3D11_FILL_SOLID;
    rsDesc.CullMode = D3D11_CULL_NONE;

    hr = device_->CreateRasterizerState(&rsDesc, &rasterizerState_);
    if (FAILED(hr)) {
        std::fprintf(stderr, "[Compositor] Failed to create rasterizer state, HR=0x%08X\n",
                     static_cast<unsigned int>(hr));
        return false;
    }

    // Depth-stencil state — depth disabled
    D3D11_DEPTH_STENCIL_DESC dsDesc = {};
    dsDesc.DepthEnable = FALSE;

    hr = device_->CreateDepthStencilState(&dsDesc, &depthStencilState_);
    if (FAILED(hr)) {
        std::fprintf(stderr, "[Compositor] Failed to create depth-stencil state, HR=0x%08X\n",
                     static_cast<unsigned int>(hr));
        return false;
    }

    return true;
}

// ===========================================================================
// Compositing
// ===========================================================================

void GridCompositor::compositeFrame(const std::vector<CellFrameRequest>& requests,
                                     RenderFrameCache& cache,
                                     int gridCols, int gridRows)
{
    if (!initialized_) return;

    auto frameStart = std::chrono::high_resolution_clock::now();

    // Count layers for logging
    int chorusCount = 0, gridCount = 0, crashCount = 0;
    for (const auto& req : requests) {
        if (req.isChorus) ++chorusCount;
        else if (req.isCrash) ++crashCount;
        else ++gridCount;
    }

    std::fprintf(stderr, "[Compositor] Frame composite: %d chorus, %d grid cells, %d crash, %d total requests\n",
                 chorusCount, gridCount, crashCount, static_cast<int>(requests.size()));

    // ── Set up pipeline state ────────────────────────────────────────────────

    // Unbind the render target SRV to avoid D3D11 read/write hazard
    ID3D11ShaderResourceView* nullSRV = nullptr;
    deviceCtx_->PSSetShaderResources(0, 1, &nullSRV);

    // Set render target
    deviceCtx_->OMSetRenderTargets(1, renderTargetRTV_.GetAddressOf(), nullptr);

    // Clear to transparent black — areas with no content will be transparent.
    // The chorus layer provides the background; gaps without chorus encode
    // as black in H.264 (which has no alpha channel).
    const float clearColor[4] = { 0.0f, 0.0f, 0.0f, 0.0f };
    deviceCtx_->ClearRenderTargetView(renderTargetRTV_.Get(), clearColor);

    // Set viewport
    D3D11_VIEWPORT viewport = {};
    viewport.Width    = static_cast<float>(width_);
    viewport.Height   = static_cast<float>(height_);
    viewport.MinDepth = 0.0f;
    viewport.MaxDepth = 1.0f;
    deviceCtx_->RSSetViewports(1, &viewport);

    // Set pipeline state
    deviceCtx_->IASetInputLayout(inputLayout_.Get());
    deviceCtx_->IASetPrimitiveTopology(D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST);

    UINT stride = sizeof(QuadVertex);
    UINT offset = 0;
    deviceCtx_->IASetVertexBuffers(0, 1, vertexBuffer_.GetAddressOf(), &stride, &offset);
    deviceCtx_->IASetIndexBuffer(indexBuffer_.Get(), DXGI_FORMAT_R16_UINT, 0);

    deviceCtx_->VSSetShader(vertexShader_.Get(), nullptr, 0);
    deviceCtx_->PSSetShader(pixelShader_.Get(), nullptr, 0);
    deviceCtx_->PSSetSamplers(0, 1, samplerState_.GetAddressOf());
    deviceCtx_->PSSetConstantBuffers(0, 1, constantBuffer_.GetAddressOf());

    float blendFactor[4] = { 0, 0, 0, 0 };
    deviceCtx_->OMSetBlendState(blendState_.Get(), blendFactor, 0xFFFFFFFF);
    deviceCtx_->RSSetState(rasterizerState_.Get());
    deviceCtx_->OMSetDepthStencilState(depthStencilState_.Get(), 0);

    // ── Pass 1: Chorus (full-screen, behind everything) ──────────────────────
    for (const auto& req : requests) {
        if (!req.isChorus) continue;

        FrameCacheKey key;
        key.sourcePath = req.sourcePath;
        key.frameIndex = req.sourceFrameIndex;
        FrameCacheEntry* entry = cache.get(key);

        if (!entry || !entry->srv) {
            std::fprintf(stderr, "[Compositor] WARN: Skipping chorus — texture is null (cache miss?)\n");
            continue;
        }

        std::fprintf(stderr, "[Compositor] Chorus: '%s' frame=%lld opacity=%.2f\n",
                     req.sourcePath.c_str(), (long long)req.sourceFrameIndex, req.opacity);

        drawCell(entry->srv.Get(), 0.0f, 0.0f, 1.0f, 1.0f,
                 req.opacity, req.flipMode, req.globalNoteIndex);
    }

    // ── Pass 2: Grid cells (each at its grid position) ───────────────────────
    for (const auto& req : requests) {
        if (req.isChorus || req.isCrash) continue;

        FrameCacheKey key;
        key.sourcePath = req.sourcePath;
        key.frameIndex = req.sourceFrameIndex;
        FrameCacheEntry* entry = cache.get(key);

        if (!entry || !entry->srv) {
            std::fprintf(stderr, "[Compositor] WARN: Skipping cell [%d,%d] — texture is null (cache miss?)\n",
                         req.cellCol, req.cellRow);
            continue;
        }

        float rx, ry, rw, rh;
        gridCellToUV(req.cellCol, req.cellRow, req.spanX, req.spanY,
                     gridCols, gridRows, rx, ry, rw, rh);

        std::fprintf(stderr, "[Compositor] Cell [%d,%d]: '%s' frame=%lld opacity=%.2f flip=%d\n",
                     req.cellCol, req.cellRow,
                     req.sourcePath.c_str(), (long long)req.sourceFrameIndex,
                     req.opacity, req.flipMode);

        drawCell(entry->srv.Get(), rx, ry, rw, rh,
                 req.opacity, req.flipMode, req.globalNoteIndex);
    }

    // ── Pass 3: Crash overlay (full-screen, on top) ──────────────────────────
    for (const auto& req : requests) {
        if (!req.isCrash) continue;

        FrameCacheKey key;
        key.sourcePath = req.sourcePath;
        key.frameIndex = req.sourceFrameIndex;
        FrameCacheEntry* entry = cache.get(key);

        if (!entry || !entry->srv) {
            std::fprintf(stderr, "[Compositor] WARN: Skipping crash — texture is null (cache miss?)\n");
            continue;
        }

        std::fprintf(stderr, "[Compositor] Crash: '%s' frame=%lld opacity=%.2f\n",
                     req.sourcePath.c_str(), (long long)req.sourceFrameIndex, req.opacity);

        drawCell(entry->srv.Get(), 0.0f, 0.0f, 1.0f, 1.0f,
                 req.opacity, req.flipMode, req.globalNoteIndex);
    }

    // Unbind render target to allow subsequent SRV reads
    ID3D11RenderTargetView* nullRTV = nullptr;
    deviceCtx_->OMSetRenderTargets(1, &nullRTV, nullptr);

    auto frameEnd = std::chrono::high_resolution_clock::now();
    double ms = std::chrono::duration<double, std::milli>(frameEnd - frameStart).count();
    std::fprintf(stderr, "[Compositor] Frame composited in %.2fms\n", ms);
}

// ===========================================================================
// Draw one cell
// ===========================================================================

void GridCompositor::drawCell(ID3D11ShaderResourceView* srv,
                               float rectX, float rectY, float rectW, float rectH,
                               float opacity, int flipMode, int globalNoteIndex)
{
    // Update constant buffer
    D3D11_MAPPED_SUBRESOURCE mapped;
    HRESULT hr = deviceCtx_->Map(constantBuffer_.Get(), 0, D3D11_MAP_WRITE_DISCARD, 0, &mapped);
    if (FAILED(hr)) return;

    CellConstants cb;
    cb.cellRect[0]     = rectX;
    cb.cellRect[1]     = rectY;
    cb.cellRect[2]     = rectW;
    cb.cellRect[3]     = rectH;
    cb.opacity         = opacity;
    cb.flipMode        = flipMode;
    cb.globalNoteIndex = globalNoteIndex;
    cb.padding         = 0.0f;

    std::memcpy(mapped.pData, &cb, sizeof(cb));
    deviceCtx_->Unmap(constantBuffer_.Get(), 0);

    // Bind texture
    deviceCtx_->PSSetShaderResources(0, 1, &srv);

    // Draw the quad (6 indices)
    deviceCtx_->DrawIndexed(6, 0, 0);
}

// ===========================================================================
// GPU→CPU readback
// ===========================================================================

ReadbackBuffer GridCompositor::readback()
{
    ReadbackBuffer buf;
    if (!initialized_) return buf;

    auto start = std::chrono::high_resolution_clock::now();

    // Copy render target to staging texture
    deviceCtx_->CopyResource(stagingTexture_.Get(), renderTarget_.Get());

    // Map staging texture
    D3D11_MAPPED_SUBRESOURCE mapped;
    HRESULT hr = deviceCtx_->Map(stagingTexture_.Get(), 0, D3D11_MAP_READ, 0, &mapped);
    if (FAILED(hr)) {
        std::fprintf(stderr, "[Compositor] Readback Map failed, HR=0x%08X\n",
                     static_cast<unsigned int>(hr));
        return buf;
    }

    buf.width  = width_;
    buf.height = height_;
    buf.stride = width_ * 4;
    buf.pixels.resize(static_cast<size_t>(buf.stride) * height_);

    // Copy row by row (staging pitch may differ from our tightly-packed stride)
    const uint8_t* src = static_cast<const uint8_t*>(mapped.pData);
    for (int y = 0; y < height_; ++y) {
        std::memcpy(buf.pixels.data() + y * buf.stride,
                    src + y * mapped.RowPitch,
                    static_cast<size_t>(buf.stride));
    }

    deviceCtx_->Unmap(stagingTexture_.Get(), 0);
    buf.valid = true;

    auto end = std::chrono::high_resolution_clock::now();
    double ms = std::chrono::duration<double, std::milli>(end - start).count();
    std::fprintf(stderr, "[Compositor] GPU readback: %dx%d → CPU buffer in %.2fms\n",
                 width_, height_, ms);

    return buf;
}

// ===========================================================================
// Grid cell → UV mapping
// ===========================================================================

void GridCompositor::gridCellToUV(int cellCol, int cellRow, int spanX, int spanY,
                                   int gridCols, int gridRows,
                                   float& outX, float& outY, float& outW, float& outH)
{
    // Half-grid: an NxM grid has 2N x 2M half-grid positions.
    // cellCol/cellRow are in half-grid coordinates.
    // spanX/spanY are in half-grid units (2 = one full cell).
    const float halfCellW = 1.0f / (gridCols * 2.0f);
    const float halfCellH = 1.0f / (gridRows * 2.0f);

    outX = cellCol * halfCellW;
    outY = cellRow * halfCellH;
    outW = spanX * halfCellW;
    outH = spanY * halfCellH;
}
